// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQ1efFKm8maD73Hnikldb3zPZOIY0u_k',
    appId: '1:956499515364:web:778d6ea61a6469d46259f1',
    messagingSenderId: '956499515364',
    projectId: 'stanley-b3c45',
    authDomain: 'stanley-b3c45.firebaseapp.com',
    databaseURL: 'https://stanley-b3c45-default-rtdb.firebaseio.com',
    storageBucket: 'stanley-b3c45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD278UEUMJ6xgVsZxIEqq_ZjgO156a0SA',
    appId: '1:956499515364:android:fe26a182a32e98d26259f1',
    messagingSenderId: '956499515364',
    projectId: 'stanley-b3c45',
    databaseURL: 'https://stanley-b3c45-default-rtdb.firebaseio.com',
    storageBucket: 'stanley-b3c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMHKpHHKFcM8-X9S_hmWENPgpSmNay5Kw',
    appId: '1:956499515364:ios:0c1898b2652fecad6259f1',
    messagingSenderId: '956499515364',
    projectId: 'stanley-b3c45',
    databaseURL: 'https://stanley-b3c45-default-rtdb.firebaseio.com',
    storageBucket: 'stanley-b3c45.appspot.com',
    iosBundleId: 'com.example.taxichrono',
  );
}
